/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package demoproject;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollBar;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;


/**
 *
 * @author AMAN
 */
public class Check extends javax.swing.JFrame {
    ArrayList<User> students = new ArrayList<>();
    /**
     * Creates new form Check
     */
    public Check() {
        initComponents();
        fillcom();
        head();
    
    }
int id;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("CHECK ACCOUNT STATUS");
        getContentPane().add(jLabel1, java.awt.BorderLayout.CENTER);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("NAME");
        getContentPane().add(jLabel2, java.awt.BorderLayout.PAGE_START);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "" }));
        jComboBox1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        getContentPane().add(jComboBox1, java.awt.BorderLayout.PAGE_END);

        jButton1.setBackground(new java.awt.Color(0, 153, 255));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("DISPLAY");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, java.awt.BorderLayout.LINE_END);

        jTable1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents
 private void head()
 {
    jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
"Pid","Date", "Type", "Pices","Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false,false,false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setCellSelectionEnabled(true);
          jScrollPane2.setViewportView(jTable1);
    jTable1 .getColumnModel().getColumn(3).setResizable(false);
 }
   

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        
       /*jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
              //  jTable1MouseClicked(evt);
            }
        });/*/
        String r=jComboBox1.getSelectedItem().toString();
        try
        {
            Dbconnection cb = new Dbconnection();
            cb.connection();
            String sql="Select * from Customer1 where Name=?";
            PreparedStatement pstm=cb.con.prepareStatement(sql);
            pstm.setString(1, r);
            ResultSet rs=pstm.executeQuery();
            while(rs.next())
            {
                id=rs.getInt("Cust_Id");
            }
        }
    
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
      
    try {
                Dbconnection cb = new Dbconnection();
            cb.connection();
               
             String sql = "select * from PurchaseDetails where Cust_Id=?";
             PreparedStatement pstmt=cb.con.prepareStatement(sql);
           pstmt.setInt(1, id);
                ResultSet rs = pstmt.executeQuery();
                if (rs.next()) {
                 
                    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                model.setRowCount(0);                   
                    fetch();
                  
                }

            } 
    catch (SQLException ex) {
                Logger.getLogger(Check.class.getName()).log(Level.SEVERE, null, ex);
            }

    }//GEN-LAST:event_jButton1ActionPerformed
    

    private void fetch() {
        students.clear();
        try {
            Dbconnection cb = new Dbconnection();
            cb.connection();
               
                      String sql = "select * from PurchaseDetails where Cust_Id="+id;
          Statement  st =cb. con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                User user = new User(rs.getInt(2),rs.getInt(3), rs.getString(4),rs.getInt(5),rs.getString(6));
                students.add(user);
            }
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            for (User user : students) {

                Object[] row = new Object[5];
                row[0] = user.getFname();
                row[1]=user.getb();
                row[2] = user.getLname();
                row[3] = user.getId();
                row[4]=user.geta();
               
                model.addRow(row);
            }

        } catch (Exception ex) {
            System.out.println(ex);
        }
 }
    private void fillcom()
    {
    try{
        String sql="Select * from Customer1";
        Dbconnection cb = new Dbconnection();
            cb.connection();
    Statement st=cb.con.createStatement();
            
            ResultSet rs=st.executeQuery(sql);
           while(rs.next()) 
           {
               String name=rs.getString("Name");
               jComboBox1.addItem(name);
                
               
           }
            
         }
        catch( Exception e)
        {
              JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Check.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Check.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Check.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Check.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Check().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
