/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package demoproject;
import java.sql.*;
import java.sql.ResultSet;
import java.sql.Statement;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;


/**
 *
 * @author AMAN
 */
public class Project extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Project() {
        initComponents();
        fillcom();
        head();
        head1();
        jTextField1.setText(dt);
         jTextField7.setText(dt);
    }
    int id,bal;
        ArrayList<User> students = new ArrayList<>();
  public static LocalDate getLocalDate()
  {
      return LocalDate.now();
  }
  String dt=String.valueOf(getLocalDate());
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        place = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        balance = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jInternalFrame3 = new javax.swing.JInternalFrame();
        jComboBox2 = new javax.swing.JComboBox();
        jButton6 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jInternalFrame4 = new javax.swing.JInternalFrame();
        jButton7 = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jComboBox3 = new javax.swing.JComboBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jInternalFrame6 = new javax.swing.JInternalFrame();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox();
        jLabel26 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTabbedPane1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        jInternalFrame1.setVisible(true);
        jInternalFrame1.getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("              ADD RECORD");
        jInternalFrame1.getContentPane().add(jLabel2);
        jLabel2.setBounds(274, 16, 388, 61);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("NAME");
        jInternalFrame1.getContentPane().add(jLabel3);
        jLabel3.setBounds(134, 83, 93, 28);

        name.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(name);
        name.setBounds(134, 117, 327, 48);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("PLACE");
        jInternalFrame1.getContentPane().add(jLabel4);
        jLabel4.setBounds(134, 176, 67, 31);

        place.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        place.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jInternalFrame1.getContentPane().add(place);
        place.setBounds(134, 213, 327, 48);

        jButton1.setBackground(new java.awt.Color(0, 153, 255));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("ADD");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jButton1);
        jButton1.setBounds(134, 400, 138, 50);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("BALANCE");
        jInternalFrame1.getContentPane().add(jLabel5);
        jLabel5.setBounds(134, 291, 95, 29);

        balance.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jInternalFrame1.getContentPane().add(balance);
        balance.setBounds(134, 326, 327, 52);

        jButton2.setBackground(new java.awt.Color(0, 153, 255));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setText("CLEAR");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jButton2);
        jButton2.setBounds(323, 400, 138, 50);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\AMAN\\Desktop\\back.png")); // NOI18N
        jLabel6.setText("jLabel6");
        jInternalFrame1.getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 980, 670);

        jTabbedPane1.addTab("ADD CUSTOMER   ", jInternalFrame1);

        jInternalFrame2.setVisible(true);
        jInternalFrame2.getContentPane().setLayout(null);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel7.setText("             UPDATE RECORD");
        jInternalFrame2.getContentPane().add(jLabel7);
        jLabel7.setBounds(298, 0, 384, 61);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("DATE");
        jInternalFrame2.getContentPane().add(jLabel8);
        jLabel8.setBounds(339, 158, 70, 30);

        jTextField1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jInternalFrame2.getContentPane().add(jTextField1);
        jTextField1.setBounds(339, 194, 200, 41);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("NO. OF PIECE");
        jInternalFrame2.getContentPane().add(jLabel9);
        jLabel9.setBounds(339, 241, 119, 29);

        jTextField2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jInternalFrame2.getContentPane().add(jTextField2);
        jTextField2.setBounds(339, 276, 200, 38);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("TYPE");
        jInternalFrame2.getContentPane().add(jLabel10);
        jLabel10.setBounds(339, 320, 82, 29);

        jTextField3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jInternalFrame2.getContentPane().add(jTextField3);
        jTextField3.setBounds(339, 355, 200, 38);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setText("AMOUNT");
        jInternalFrame2.getContentPane().add(jLabel11);
        jLabel11.setBounds(339, 399, 81, 26);

        jTextField4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jInternalFrame2.getContentPane().add(jTextField4);
        jTextField4.setBounds(339, 431, 200, 38);

        jButton3.setBackground(new java.awt.Color(0, 153, 255));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton3.setText("SAVE");
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jInternalFrame2.getContentPane().add(jButton3);
        jButton3.setBounds(262, 487, 147, 50);

        jButton4.setBackground(new java.awt.Color(0, 153, 255));
        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton4.setText("CLEAR");
        jButton4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jInternalFrame2.getContentPane().add(jButton4);
        jButton4.setBounds(505, 487, 141, 50);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setText("NAME");
        jInternalFrame2.getContentPane().add(jLabel12);
        jLabel12.setBounds(339, 79, 61, 29);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "" }));
        jComboBox1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jInternalFrame2.getContentPane().add(jComboBox1);
        jComboBox1.setBounds(339, 114, 200, 44);

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jLabel13.setOpaque(true);
        jInternalFrame2.getContentPane().add(jLabel13);
        jLabel13.setBounds(565, 114, 216, 44);

        jButton5.setBackground(new java.awt.Color(0, 153, 255));
        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton5.setText("SHOW");
        jButton5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jInternalFrame2.getContentPane().add(jButton5);
        jButton5.setBounds(799, 120, 47, 21);

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\AMAN\\Desktop\\back.png")); // NOI18N
        jLabel14.setText("jLabel8");
        jInternalFrame2.getContentPane().add(jLabel14);
        jLabel14.setBounds(0, -20, 1080, 690);

        jTabbedPane1.addTab("PURCHASE DETAILS   ", jInternalFrame2);

        jInternalFrame3.setVisible(true);
        jInternalFrame3.getContentPane().setLayout(null);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "" }));
        jComboBox2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jInternalFrame3.getContentPane().add(jComboBox2);
        jComboBox2.setBounds(346, 120, 126, 43);

        jButton6.setBackground(new java.awt.Color(0, 153, 255));
        jButton6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton6.setText("DISPLAY");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jInternalFrame3.getContentPane().add(jButton6);
        jButton6.setBounds(370, 470, 129, 45);

        jTable1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jInternalFrame3.getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(340, 190, 305, 237);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel15.setText("CHECK ACCOUNT STATUS");
        jInternalFrame3.getContentPane().add(jLabel15);
        jLabel15.setBounds(270, 21, 317, 63);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel16.setText("NAME");
        jInternalFrame3.getContentPane().add(jLabel16);
        jLabel16.setBounds(220, 132, 80, 31);

        jLabel21.setIcon(new javax.swing.ImageIcon("C:\\Users\\AMAN\\Desktop\\back.png")); // NOI18N
        jLabel21.setText("jLabel8");
        jInternalFrame3.getContentPane().add(jLabel21);
        jLabel21.setBounds(0, 0, 1210, 660);

        jTabbedPane1.addTab("CHECK STATUS   ", jInternalFrame3);

        jInternalFrame4.setVisible(true);
        jInternalFrame4.getContentPane().setLayout(null);

        jButton7.setBackground(new java.awt.Color(0, 153, 255));
        jButton7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton7.setText("UPDATE");
        jButton7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jInternalFrame4.getContentPane().add(jButton7);
        jButton7.setBounds(596, 573, 121, 44);

        jTextField5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTextField5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jInternalFrame4.getContentPane().add(jTextField5);
        jTextField5.setBounds(401, 190, 131, 43);

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel17.setText("PICES");
        jInternalFrame4.getContentPane().add(jLabel17);
        jLabel17.setBounds(267, 194, 69, 34);

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel18.setText("DELETE RECORD");
        jInternalFrame4.getContentPane().add(jLabel18);
        jLabel18.setBounds(236, 30, 263, 64);

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel19.setText("AMOUNT");
        jInternalFrame4.getContentPane().add(jLabel19);
        jLabel19.setBounds(250, 261, 90, 31);

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel20.setText("NAME");
        jInternalFrame4.getContentPane().add(jLabel20);
        jLabel20.setBounds(267, 133, 80, 31);

        jTextField6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTextField6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jInternalFrame4.getContentPane().add(jTextField6);
        jTextField6.setBounds(401, 254, 131, 45);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "" }));
        jComboBox3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jInternalFrame4.getContentPane().add(jComboBox3);
        jComboBox3.setBounds(401, 129, 126, 43);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        jInternalFrame4.getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(360, 318, 305, 237);

        jButton8.setBackground(new java.awt.Color(0, 153, 255));
        jButton8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton8.setText("DISPLAY");
        jButton8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jInternalFrame4.getContentPane().add(jButton8);
        jButton8.setBounds(236, 573, 129, 45);

        jButton9.setBackground(new java.awt.Color(0, 153, 255));
        jButton9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton9.setText("CLEAR");
        jButton9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jInternalFrame4.getContentPane().add(jButton9);
        jButton9.setBounds(758, 573, 127, 45);

        jButton10.setBackground(new java.awt.Color(0, 153, 255));
        jButton10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton10.setText("DELETE");
        jButton10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jInternalFrame4.getContentPane().add(jButton10);
        jButton10.setBounds(423, 573, 127, 44);

        jLabel29.setIcon(new javax.swing.ImageIcon("C:\\Users\\AMAN\\Desktop\\back.png")); // NOI18N
        jLabel29.setText("jLabel8");
        jInternalFrame4.getContentPane().add(jLabel29);
        jLabel29.setBounds(0, 0, 1080, 660);

        jTabbedPane1.addTab("MODIFY PURCHASE DETIALS   ", jInternalFrame4);

        jInternalFrame6.setVisible(true);
        jInternalFrame6.getContentPane().setLayout(null);

        jLabel22.setBackground(java.awt.Color.lightGray);
        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel22.setText("                PAYMENT");
        jLabel22.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jLabel22.setOpaque(true);
        jInternalFrame6.getContentPane().add(jLabel22);
        jLabel22.setBounds(332, 30, 306, 59);

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel23.setText("BALANCE");
        jInternalFrame6.getContentPane().add(jLabel23);
        jLabel23.setBounds(336, 443, 87, 26);

        jTextField7.setEditable(false);
        jTextField7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jInternalFrame6.getContentPane().add(jTextField7);
        jTextField7.setBounds(340, 190, 187, 37);

        jLabel24.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel24.setText("DATE");
        jInternalFrame6.getContentPane().add(jLabel24);
        jLabel24.setBounds(336, 155, 54, 27);

        jTextField8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        jInternalFrame6.getContentPane().add(jTextField8);
        jTextField8.setBounds(340, 330, 187, 37);

        jButton11.setBackground(new java.awt.Color(0, 153, 255));
        jButton11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton11.setText("SHOW");
        jButton11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jInternalFrame6.getContentPane().add(jButton11);
        jButton11.setBounds(560, 323, 90, 40);

        jLabel25.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel25.setText("NAME");
        jInternalFrame6.getContentPane().add(jLabel25);
        jLabel25.setBounds(336, 231, 54, 23);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        jComboBox4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jComboBox4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox4MouseClicked(evt);
            }
        });
        jInternalFrame6.getContentPane().add(jComboBox4);
        jComboBox4.setBounds(336, 255, 118, 36);

        jLabel26.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel26.setText("REMAINING");
        jInternalFrame6.getContentPane().add(jLabel26);
        jLabel26.setBounds(336, 297, 108, 25);

        jTextField9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jTextField9.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        jInternalFrame6.getContentPane().add(jTextField9);
        jTextField9.setBounds(340, 400, 187, 37);

        jLabel27.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel27.setText("PAID");
        jInternalFrame6.getContentPane().add(jLabel27);
        jLabel27.setBounds(336, 371, 93, 23);

        jTextField10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        jInternalFrame6.getContentPane().add(jTextField10);
        jTextField10.setBounds(340, 490, 187, 37);

        jButton12.setBackground(new java.awt.Color(0, 153, 255));
        jButton12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton12.setText("SAVE");
        jButton12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jInternalFrame6.getContentPane().add(jButton12);
        jButton12.setBounds(254, 548, 147, 50);

        jButton13.setBackground(new java.awt.Color(0, 153, 255));
        jButton13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton13.setText("CLEAR");
        jButton13.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jInternalFrame6.getContentPane().add(jButton13);
        jButton13.setBounds(497, 548, 141, 50);

        jLabel28.setIcon(new javax.swing.ImageIcon("C:\\Users\\AMAN\\Desktop\\back.png")); // NOI18N
        jLabel28.setText("jLabel8");
        jInternalFrame6.getContentPane().add(jLabel28);
        jLabel28.setBounds(0, -20, 1080, 660);

        jTabbedPane1.addTab("PAYMENT   ", jInternalFrame6);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1099, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(405, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(263, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 60, 1200, 860);

        jLabel30.setText("jLabel30");
        getContentPane().add(jLabel30);
        jLabel30.setBounds(0, 0, 40, 14);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        jTextField7.setText("");
        jTextField8.setText("");
        jTextField9.setText("");
        jTextField10.setText("");
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:

        try
        {
            Dbconnection cb = new Dbconnection();
            int b,c,d;
String a;
            a=jTextField7.getText();
            b=Integer.parseInt(jTextField8.getText());
            c=Integer.parseInt(jTextField9.getText());
            d=b-c;
            jTextField10.setText(String.valueOf(d));
            d=Integer.parseInt(jTextField10.getText());

            cb.connection();
            String sql1="insert into PaymentDetails values("+id+","+a+",'"+b+"',"+c+","+d+")";
            Statement st1=cb.con.createStatement();
            st1.execute(sql1);
            String sql2="update  Customer1 set Balance="+d+"where Cust_Id="+id;
            Statement st2=cb.con.createStatement();
            st2.execute(sql2);
            JOptionPane.showMessageDialog(this, "Recored entered!!!");
        }
        catch( Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jComboBox4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4MouseClicked

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        String r=jComboBox4.getSelectedItem().toString();
        try
        {
            Dbconnection cb = new Dbconnection();
            cb.connection();
            String sql="Select * from Customer1 where Name=?";
            PreparedStatement pstm=cb.con.prepareStatement(sql);
            pstm.setString(1, r);
            ResultSet rs=pstm.executeQuery();
            while(rs.next())
            {
                id=rs.getInt("Cust_Id");
                bal=rs.getInt("Balance");
            }
        }

        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        jTextField8.setText(String.valueOf(bal));
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        int i = jTable2.getSelectedRow();
        if (i >= 0) {
            int option = JOptionPane.showConfirmDialog(rootPane,
                "Are you sure you want to Delete?", "Delete confirmation", JOptionPane.YES_NO_OPTION);
            if (option == 0) {
                TableModel model = jTable2.getModel();

                String Pid= model.getValueAt(i, 0).toString();
                if (jTable2.getSelectedRows().length == 1) {
                    delete(Pid);
                    DefaultTableModel model1 = (DefaultTableModel) jTable2.getModel();
                    model1.setRowCount(0);
                    fetch1();
                }
            }
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        jTextField5.setText("");
        jTextField6.setText("");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:

        /*jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                //  jTable1MouseClicked(evt);
            }
        });/*/
        String r=jComboBox3.getSelectedItem().toString();
        try
        {
            Dbconnection cb = new Dbconnection();
            cb.connection();
            String sql="Select * from Customer1 where Name=?";
            PreparedStatement pstm=cb.con.prepareStatement(sql);
            pstm.setString(1, r);
            ResultSet rs=pstm.executeQuery();
            while(rs.next())
            {
                id=rs.getInt("Cust_Id");
            }
        }

        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }

        try {
            Dbconnection cb = new Dbconnection();
            cb.connection();

            String sql = "select * from PurchaseDetails where Cust_Id=?";
            PreparedStatement pstmt=cb.con.prepareStatement(sql);
            pstmt.setInt(1, id);
            ResultSet rs = pstmt.executeQuery();
            if (rs.next()) {

                DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
                model.setRowCount(0);
                fetch1();

            }

        }
        catch (SQLException ex) {
            Logger.getLogger(Check.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        int i = jTable2.getSelectedRow();
        if (i >= 0) {
            int option = JOptionPane.showConfirmDialog(rootPane,
                "Do You Want To Update?", "Update confirmation", JOptionPane.YES_NO_OPTION);
            if (option == 0) {
                TableModel model = jTable2.getModel();

                String Pid= model.getValueAt(i, 0).toString();
                String Pices=jTextField5.getText();
                String Amount=jTextField6.getText();
                if (jTable2.getSelectedRows().length == 1) {
                    update(Pid,Pices,Amount);
                    DefaultTableModel model1 = (DefaultTableModel) jTable2.getModel();
                    model1.setRowCount(0);
                    fetch1();
                }
            }
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:

        /*jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                //  jTable1MouseClicked(evt);
            }
        });/*/
        String r=jComboBox1.getSelectedItem().toString();
        try
        {
            Dbconnection cb = new Dbconnection();
            cb.connection();
            String sql="Select * from Customer1 where Name=?";
            PreparedStatement pstm=cb.con.prepareStatement(sql);
            pstm.setString(1, r);
            ResultSet rs=pstm.executeQuery();
            while(rs.next())
            {
                id=rs.getInt("Cust_Id");
            }
        }

        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }

        try {
            Dbconnection cb = new Dbconnection();
            cb.connection();

            String sql = "select * from PurchaseDetails where Cust_Id=?";
            PreparedStatement pstmt=cb.con.prepareStatement(sql);
            pstmt.setInt(1, id);
            ResultSet rs = pstmt.executeQuery();
            if (rs.next()) {

                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                model.setRowCount(0);
                fetch();

            }

        }
        catch (SQLException ex) {
            Logger.getLogger(Check.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String r=jComboBox1.getSelectedItem().toString();
        try
        {
            Dbconnection cb = new Dbconnection();
            cb.connection();
            String sql="Select * from Customer1 where Name=?";
            PreparedStatement pstm=cb.con.prepareStatement(sql);
            pstm.setString(1, r);
            ResultSet rs=pstm.executeQuery();
            while(rs.next())
            {
                id=rs.getInt("Cust_Id");
                bal=rs.getInt("Balance");
            }
        }

        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        jLabel13.setText("Remaining "+bal);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jLabel13.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        String r=jComboBox1.getSelectedItem().toString();
        try
        {
            Dbconnection cb = new Dbconnection();
            cb.connection();
            String sql="Select * from Customer1 where Name=?";
            PreparedStatement pstm=cb.con.prepareStatement(sql);
            pstm.setString(1, r);
            ResultSet rs=pstm.executeQuery();
            while(rs.next())
            {
                id=rs.getInt("Cust_Id");
            }
        }

        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }

        try
        {
            Dbconnection cb = new Dbconnection();
            int b,c,e;
            String d,a; 
            a=jTextField1.getText();
            b=Integer.parseInt(jTextField2.getText());
            c=Integer.parseInt(jTextField4.getText());
            d=jTextField3.getText();
            e=bal+c;
            cb.connection();
            String sql="insert into PurchaseDetails values("+id+","+a+",'"+d+"',"+b+","+c+")";
            Statement st=cb.con.createStatement();
            st.execute(sql);
            String sql1="update Customer1 set Balance="+e+"where Cust_Id="+id;
            st.execute(sql1);
            JOptionPane.showMessageDialog(this, "Recored entered!!!");
        }
        catch( Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        name.setText("");
        place.setText("");
        balance.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try
        {
            Dbconnection cb = new Dbconnection();
            cb.connection();
            String tb=name.getText();
            String pc;
            pc=place.getText();
            int  bal;
            bal = Integer.parseInt(balance.getText());

            String sql="insert into Customer1 values('"+tb+"','"+pc+"',"+bal+")";
            Statement st=cb.con.createStatement();
            st.execute(sql);
            JOptionPane.showMessageDialog(this, "Recored entered!!!");

        }
        catch( Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed
private void head()
 {
    jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
"Pid","Date", "Type", "Pices","Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false,false,false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setCellSelectionEnabled(true);
          jScrollPane2.setViewportView(jTable1);
    jTable1 .getColumnModel().getColumn(3).setResizable(false);
 }
private void head1()
 {
    jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
"Pid","Date", "Type", "Pices","Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false,false,false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setCellSelectionEnabled(true);
          jScrollPane3.setViewportView(jTable2);
    jTable2 .getColumnModel().getColumn(3).setResizable(false);
 }

public void delete(String Pid) {
        try {
            Dbconnection cb = new Dbconnection();
            cb.connection();
            String sql = "DELETE FROM PurchaseDetails WHERE Pid=?";
             PreparedStatement pstmt=cb.con.prepareStatement(sql);
             Integer.parseInt(Pid);
            pstmt.setString(1, Pid);
            pstmt.execute();
        } catch (SQLException ex) {
            Logger.getLogger(Check.class.getName()).log(Level.SEVERE, null, ex);
        }
       fetch();
    }
     public void update(String Pid,String Pices,String Amount) {
        try {
            Dbconnection cb = new Dbconnection();
            cb.connection();
            String sql = "update PurchaseDetails set Pices=?,Amount=? where Pid=?";
             PreparedStatement pstmt=cb.con.prepareStatement(sql);
              Integer.parseInt(Pices);
            pstmt.setString(1, Pices);
             Integer.parseInt(Amount);
            pstmt.setString(2,Amount);
             Integer.parseInt(Pid);
            pstmt.setString(3, Pid);
            pstmt.execute();
        } catch (SQLException ex) {
            Logger.getLogger(Check.class.getName()).log(Level.SEVERE, null, ex);
        }
       fetch();
    }
   
    private void fillcom()
    {
    try{
        String sql="Select * from Customer1";
        Dbconnection cb = new Dbconnection();
            cb.connection();
    Statement st=cb.con.createStatement();
            
            ResultSet rs=st.executeQuery(sql); 
           while(rs.next()) 
           {
               String name=rs.getString("Name");
               jComboBox1.addItem(name);
                jComboBox2.addItem(name);
                jComboBox3.addItem(name);
                jComboBox4.addItem(name);
               
           }
           
            
         }
        catch( Exception e)
        {
              JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }
    
    private void fetch() {
        students.clear();
        try {
            Dbconnection cb = new Dbconnection();
            cb.connection();
               
                      String sql = "select * from PurchaseDetails where Cust_Id="+id;
          Statement  st =cb. con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                User user = new User(rs.getInt(2),rs.getInt(3), rs.getString(4),rs.getInt(5),rs.getString(6));
                students.add(user);
            }
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            for (User user : students) {

                Object[] row = new Object[5];
                row[0] = user.getFname();
                row[1]=user.getb();
                row[2] = user.getLname();
                row[3] = user.getId();
                row[4]=user.geta();
               
                model.addRow(row);
            }

        } catch (Exception ex) {
            System.out.println(ex);
        }
    }
     private void fetch1() {
        students.clear();
        try {
            Dbconnection cb = new Dbconnection();
            cb.connection();
               
                      String sql = "select * from PurchaseDetails where Cust_Id="+id;
          Statement  st =cb. con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                User user = new User(rs.getInt(2),rs.getInt(3), rs.getString(4),rs.getInt(5),rs.getString(6));
                students.add(user);
            }
            DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
            for (User user : students) {

                Object[] row = new Object[5];
                row[0] = user.getFname();
                row[1]=user.getb();
                row[2] = user.getLname();
                row[3] = user.getId();
                row[4]=user.geta();
               
                model.addRow(row);
            }

        } catch (Exception ex) {
            System.out.println(ex);
        }
     }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Project().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField balance;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JInternalFrame jInternalFrame3;
    private javax.swing.JInternalFrame jInternalFrame4;
    private javax.swing.JInternalFrame jInternalFrame6;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField name;
    private javax.swing.JTextField place;
    // End of variables declaration//GEN-END:variables
}
